---
version: '2.1'
services:
  postgres:
    image: postgres
    env_file:
      - .env
      - .env.development
    ports:
      - "5432:5432"
    volumes:
      - 'postgres:/var/lib/postgresql/data'
  web:
    build: .
    image: "${REGISTRY_HOST}${REGISTRY_URI}/${TAG}"
    command: bash -c "bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/webapp
    env_file:
      - .env
      - .env.development
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - postgres
  # webpacker:
  #   image: "${REGISTRY_HOST}${REGISTRY_URI}/${TAG}"
  #   command: bash -c "./bin/webpack --watch --colors --progress"
  #   volumes:
  #     - .:/webapp
  #   env_file:
  #     - .env
  #     - .env.development

volumes:
  postgres:
